version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel_app
    working_dir: /var/www/html
    volumes:
      - .:/var/www/html
    ports:
      - "8000:80"  
    environment:
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=genie
      - DB_USERNAME=root
      - DB_PASSWORD=secret
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: genie_mysql_db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: genie
    volumes:
      - dbdata:/var/lib/mysql
    ports:
      - "3307:3306"  

volumes:
  dbdata:
