version: "3.7"
services:
  app:
    build:
      args:
        user: thabiso # Replace with your actual username
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    image: genie_app
    container_name: genie_app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    networks:
      - genie-network

  db:
    image: mysql:8.0
    container_name: genie_db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - ./docker-compose/mysql:/docker-entrypoint-initdb.d
    networks:
      - genie-network

  nginx:
    image: nginx:alpine
    container_name: genie_nginx
    restart: unless-stopped
    ports:
      - 8000:80
    volumes:
      - ./:/var/www
      - ./docker-compose/nginx:/etc/nginx/conf.d/
    networks:
      - genie-network

networks:
  genie-network:
    driver: bridge
